### ISSUE TITLE
Retry failed IPFS downloads with multiple HTTP gateways

### ISSUE THREAD

**Issue by thomshutt** [livepeer/catalyst-api#350]
We should begin with a list of 3-4 preferred gateways and then when the IPFS download stage fails, iterate through these.

For an example of where we do this on Studio, see: https://github.com/livepeer/task-runner/blob/6853b65ac1ba193e59875e6a04383d73d0744972/task/import.go#L126

@victorges is the best person to consult on questions as he implemented the above and has information on the dedicated Piñata gateway that should be our first option.

**Comment by victorges** [comment]
Other resources from the existing implementation:
 - the config with the list of gateways that we can just copy to the catalyst config: https://github.com/livepeer/livepeer-infra/blob/4da583548d7ea7c1f11c14dbfda1715f2cd8c943/values/task-runner.values.yaml#L9
 - the helper CLI flag parsing code for URLs: https://github.com/livepeer/task-runner/blob/66ef87d7135321eb4fafc8e667a6db092fa77c46/cmd/task-runner/task-runner.go#L48
 - how these flags are then used: https://github.com/livepeer/task-runner/blob/6853b65ac1ba193e59875e6a04383d73d0744972/task/import.go#L126

Notice that we do need to parse the URLs at some point in the code in order to build the full file URLs, since the private Piñata gateway that we have has a query-string in the base URL for the auth token, meaning we can't just string-concat the base URL with the CID to get the full URL. I decided to make the parsing on the CLI-side on task-runner to make the core logic cleaner and also get automatic startup errors if invalid URLs are provided (instead of errors only when they are eventually used). I recommend following the same approach because of that.
