### ISSUE TITLE
Update output video response to Studio

### ISSUE THREAD

**Issue by emranemran** [livepeer/catalyst-api#419]
Follow-up on Victor's comment from here: 
https://github.com/livepeer/catalyst-api/issues/400

**Comment by mjh1** [comment]
So in line with @victorges's [comment](https://github.com/livepeer/catalyst-api/issues/400#issuecomment-1410773385), reducing to a single output with optional hls and mp4 outputs, this is a first suggestion:

```
{
    "outputs": [
        {
            "type": "object_store",
            "manifest": "https://foo.bar/index.m3u8",
            "mp4_outputs": [
                {
                    "size": "123456",
                    "location": "https://foo.bar/static360p0.mp4",
                    "height": 123,
                    "width": 123,
                    "bitrate": 123
                },
                {
                    "size": "1234567",
                    "location": "https://foo.bar/static720p0.mp4",
                    "height": 123,
                    "width": 123,
                    "bitrate": 123
                }
            ]
        }
    ]
}
```

It also then makes it easy for consumers like studio to pick out the mp4 outputs.
@victorges @emranemran @gioelecerati what do you guys think?
cc @thomshutt

**Comment by emranemran** [comment]
Yep, I like this style. 

@victorges / @gioelecerati, can you guys confirm?

**Comment by victorges** [comment]
@mjh1 @emranemran I like it too! Just to confirm we're aligned E2E: then the corresponding output_locations in the request would be a single entry with both `transcoded_segments` and `auto_mp4s` turned on, with the path set to the asset folder instead of a specific file (today, HLS index). Then catalyst figures out the relative paths and returns them in that response. Is that it?

**Comment by mjh1** [comment]
> 

Exactly, that's what I was thinking yep.
